//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class basfenvironmental
    {
        public string id { get; set; }
        public string incidentdate { get; set; }
        public string incidenttime { get; set; }
        public string callername { get; set; }
        public string callerphone { get; set; }
        public string plantname { get; set; }
        public string materialname { get; set; }
        public string sdsonhand { get; set; }
        public string contained { get; set; }
        public string handlingcleanup { get; set; }
        public string description { get; set; }
        public string quantity { get; set; }
        public string quantityunits { get; set; }
        public string releaseto { get; set; }
        public string actions { get; set; }
        public string achievereportablequantity { get; set; }
        public string notifications { get; set; }
        public string ersoperator { get; set; }
        public string calldate { get; set; }
        public string calltime { get; set; }
        public string nrc { get; set; }
        public string peas { get; set; }
    }
}
