//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class crestdotincident
    {
        public int id { get; set; }
        public string callername { get; set; }
        public string callertitle { get; set; }
        public string calleraffiliation { get; set; }
        public string callerphonenumber { get; set; }
        public string incidentdate { get; set; }
        public string incidentlocation { get; set; }
        public string incidentlatitude { get; set; }
        public string incidentlongitude { get; set; }
        public string incidentoccuron { get; set; }
        public string incidentnature { get; set; }
        public string incidentdescription { get; set; }
        public string involvedname1 { get; set; }
        public string involvedcell1 { get; set; }
        public string involvedinjury1 { get; set; }
        public string involvedname2 { get; set; }
        public string involvedcell2 { get; set; }
        public string involvedinjury2 { get; set; }
        public string involvedname3 { get; set; }
        public string involvedcell3 { get; set; }
        public string involvedinjury3 { get; set; }
        public string weatherconditions { get; set; }
        public string impactedareas { get; set; }
        public string impactedbodyofwater { get; set; }
        public string reporttakername { get; set; }
        public string reporttakeremail { get; set; }
        public string ersname1 { get; set; }
        public string erscontactnumber1 { get; set; }
        public string erslocation1 { get; set; }
        public string ersname2 { get; set; }
        public string erscontactnumber2 { get; set; }
        public string erslocation2 { get; set; }
        public string ersname3 { get; set; }
        public string erscontactnumber3 { get; set; }
        public string erslocation3 { get; set; }
        public string dispatcheroremployee { get; set; }
        public string contractororemployee { get; set; }
    }
}
