//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class crestwoodtransportationlist
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> Indiana { get; set; }
        public Nullable<int> NewJersey { get; set; }
        public Nullable<int> WestVirginia { get; set; }
    }
}
