//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class crestpiplineincident
    {
        public int id { get; set; }
        public string county { get; set; }
        public string state { get; set; }
        public string distancefromtown { get; set; }
        public string distancefromlandmark { get; set; }
        public string intersectionormilemarker { get; set; }
        public string observing { get; set; }
        public string seeinghearingsmelling { get; set; }
        public string roworwellpad { get; set; }
        public string tanks { get; set; }
        public string landowner { get; set; }
        public string callername { get; set; }
        public string callerphone { get; set; }
        public string notify911 { get; set; }
        public string anyoneinjured { get; set; }
        public string immediatedanger { get; set; }
        public string temp { get; set; }
        public string windspeed { get; set; }
        public string winddirection { get; set; }
        public string weatherconditions { get; set; }
        public string relationtoincident { get; set; }
        public string safelywarn { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public string name3 { get; set; }
        public string contactnumber1 { get; set; }
        public string contactnumber2 { get; set; }
        public string contactnumber3 { get; set; }
        public string location1 { get; set; }
        public string location2 { get; set; }
        public string location3 { get; set; }
        public string leasewellname { get; set; }
        public string blackorwhitesmoke { get; set; }
        public string flames { get; set; }
        public string hissing { get; set; }
        public string liquid { get; set; }
        public string oilysheen { get; set; }
        public string otherpipelinemarkers { get; set; }
        public string rotteneggodor { get; set; }
        public string vaporormist { get; set; }
        public string directions { get; set; }
        public string city { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public string timezone { get; set; }
        public int numofinjuries { get; set; }
        public string reporttakername { get; set; }
        public string reporttakeremail { get; set; }
        public string description { get; set; }
        public string calleremail { get; set; }
        public string callertitle { get; set; }
        public string calleraffiliation { get; set; }
        public string name4 { get; set; }
        public string name5 { get; set; }
        public string contactnumber4 { get; set; }
        public string contactnumber5 { get; set; }
        public string location4 { get; set; }
        public string location5 { get; set; }
        public string calldate { get; set; }
        public string calltime { get; set; }
        public string ersoperator { get; set; }
        public string initials { get; set; }
        public string NotificationDate { get; set; }
        public string NotificationTime { get; set; }
        public string Drill { get; set; }
    }
}
