//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class crestgeneralincident
    {
        public int id { get; set; }
        public string callername { get; set; }
        public string callertitle { get; set; }
        public string calleraffiliation { get; set; }
        public string callerphonenumber { get; set; }
        public System.DateTime incidentdate { get; set; }
        public string incidentlocation { get; set; }
        public string incidentlatitude { get; set; }
        public string incidentlongitude { get; set; }
        public string incidentoccuron { get; set; }
        public string incidentnature { get; set; }
        public string incidentdescription { get; set; }
        public string involvedname1 { get; set; }
        public string involvedcell1 { get; set; }
        public string involvedinjury1 { get; set; }
        public string involvedname2 { get; set; }
        public string involvedcell2 { get; set; }
        public string involvedinjury2 { get; set; }
        public string involvedname3 { get; set; }
        public string involvedcell3 { get; set; }
        public string involvedinjury3 { get; set; }
        public string weatherconditions { get; set; }
        public string impactedareas { get; set; }
        public string impactedbodyofwater { get; set; }
        public string reporttakername { get; set; }
        public string reporttakeremail { get; set; }
        public string ersname1 { get; set; }
        public string erscontactnumber1 { get; set; }
        public string erslocation1 { get; set; }
        public string ersname2 { get; set; }
        public string erscontactnumber2 { get; set; }
        public string erslocation2 { get; set; }
        public string ersname3 { get; set; }
        public string erscontactnumber3 { get; set; }
        public string erslocation3 { get; set; }
        public string incidentprivaterow { get; set; }
        public string incidenttriballand { get; set; }
        public string incidentblmland { get; set; }
        public string incidentstateland { get; set; }
        public string incidentaddress { get; set; }
        public string incidentcity { get; set; }
        public string incidentstate { get; set; }
        public string incidentcounty { get; set; }
        public string incidentintersection { get; set; }
        public string incidentfacilityname { get; set; }
        public string fireorexplosion { get; set; }
        public string pipelinestrike { get; set; }
        public string injury { get; set; }
        public string illnessorexposure { get; set; }
        public string vehicleaccident { get; set; }
        public string spillorrelease { get; set; }
        public string theft { get; set; }
        public string agencyinspectionofvisit { get; set; }
        public string propertydamage { get; set; }
        public string potentialhazardornearmiss { get; set; }
        public string landownercomplaint { get; set; }
        public string impactstowater { get; set; }
        public string dispatcheroremployee { get; set; }
        public string contractororemployee { get; set; }
        public string notify911 { get; set; }
        public string immediatesupport { get; set; }
        public string transporttohospital { get; set; }
        public string emergencyresponders { get; set; }
        public string fatalities { get; set; }
        public string mediaonscene { get; set; }
        public string landowner { get; set; }
        public string incidenttime { get; set; }
        public string incidenttimezone { get; set; }
        public string calleremail { get; set; }
        public string calldate { get; set; }
        public string calltime { get; set; }
        public string other { get; set; }
        public string ersoperator { get; set; }
        public string equipmentorpeople { get; set; }
        public string numinjuries1 { get; set; }
        public string numinjuries2 { get; set; }
        public string numinjuries3 { get; set; }
        public string none { get; set; }
        public string unknown { get; set; }
        public string tractortrailer { get; set; }
        public string equipment { get; set; }
        public string dispatcheremployee { get; set; }
        public string initials { get; set; }
        public string county { get; set; }
        public string drill { get; set; }
        public string Incident_Contractor_Or_Employee { get; set; }
        public string IndividualSafety { get; set; }
        public string WeaponReported { get; set; }
        public string WeaponType { get; set; }
        public string wpviolence { get; set; }
        public string FacilityOrProject { get; set; }
        public string RegionOrFacility { get; set; }
        public string ContractorName { get; set; }
        public string FacilityOrProjectSelection { get; set; }
        public string OccuredOnPipeline { get; set; }
        public string NotificationDate { get; set; }
        public string NotificationTime { get; set; }
        public string PC_CWLocOrTransport { get; set; }
        public string SusAct { get; set; }
        public string SpillOrReleaseIntoAtmo { get; set; }
        public string MaterialSpilled { get; set; }
        public string WaterbodiesImpacted { get; set; }
        public string ContainedOnSite { get; set; }
        public string SpillContainedSecondary { get; set; }
        public string ControlDevices { get; set; }
        public string PrimaryWorkLocation { get; set; }
    }
}
