//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class crest811
    {
        public int id { get; set; }
        public string todaydate { get; set; }
        public string todaytime { get; set; }
        public string excavationdate { get; set; }
        public string excavationtime { get; set; }
        public string normaloremergency { get; set; }
        public string requestticketnumber { get; set; }
        public string personcompanyname { get; set; }
        public string callbacknumber { get; set; }
        public string emailaddress { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string county { get; set; }
        public string workdate { get; set; }
        public string street { get; set; }
        public string intersection { get; set; }
        public string nature { get; set; }
        public string remarks { get; set; }
        public string callername { get; set; }
        public string callernumber { get; set; }
        public string name { get; set; }
        public string contactnumber { get; set; }
        public string location { get; set; }
        public string FacilityName { get; set; }
    }
}
