//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalincidentreportdata
    {
        public string IncidentId { get; set; }
        public string ErsOperator { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string CallersName { get; set; }
        public string CallersPhone { get; set; }
        public string CallersAffiliation { get; set; }
        public string CallersFaxOrEmail { get; set; }
        public string IncidentStreet { get; set; }
        public string IncidentCity { get; set; }
        public string IncidentState { get; set; }
        public string IncidentCountry { get; set; }
        public string IncidentDate { get; set; }
        public string IncidentTime { get; set; }
        public string IncidentTimeZone { get; set; }
        public string MaterialName { get; set; }
        public string ProductNumber { get; set; }
        public string QuantitySpilled { get; set; }
        public string CleanUpCrewReqs { get; set; }
        public string AgenciesOnSite { get; set; }
        public string AccidentOrDeliberate { get; set; }
        public string IncidentDetails { get; set; }
        public string InvolveFire { get; set; }
        public string WhereDidYouGetOurNumber { get; set; }
        public string SubscribersName { get; set; }
        public string SubscriberMIS { get; set; }
        public string SpillOrExposure { get; set; }
        public string TypeOfExposure { get; set; }
        public string NumOfCasualties { get; set; }
        public string NumOfInjuries { get; set; }
        public string MedPersonnelName { get; set; }
        public string PatientName { get; set; }
        public string PatientCondition { get; set; }
        public string HospitalClinicLocation { get; set; }
        public string EpaRegNo { get; set; }
        public string StatusOfRelease { get; set; }
        public string DispersionOfMsdsInfo { get; set; }
        public string ReviewedBy { get; set; }
        public string ReviewedDate { get; set; }
        public string SentDate { get; set; }
        public string Comments { get; set; }
        public string DateChanged { get; set; }
        public string Username { get; set; }
        public string IncidentZipCode { get; set; }
        public string ReportType { get; set; }
        public string CallersPhoneExt { get; set; }
    }
}
