//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class glocountylist
    {
        public double countyCode { get; set; }
        public string countyName { get; set; }
        public string countyGLOVoiceNumber { get; set; }
        public string countyGLORegionNumber { get; set; }
        public string countyGLORegionCity { get; set; }
        public string countyGLOBeeperNumber { get; set; }
        public string countyRRCNumber { get; set; }
        public string countyRRCDistrictNumber { get; set; }
        public string countyRRCDistrictCity { get; set; }
        public string countyTNRCCNumber { get; set; }
        public string countyTNRCCDistrictNumber { get; set; }
        public string countyTNRCCDistrictCity { get; set; }
    }
}
