//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class gloemail
    {
        public long id { get; set; }
        public string name { get; set; }
        public string emailgroup { get; set; }
        public string email01 { get; set; }
        public string email02 { get; set; }
        public string email03 { get; set; }
        public string email04 { get; set; }
        public string email05 { get; set; }
        public string email06 { get; set; }
        public string email07 { get; set; }
        public string email08 { get; set; }
        public string email09 { get; set; }
        public string email10 { get; set; }
    }
}
