//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chemreporterEntities : DbContext
    {
        public chemreporterEntities()
            : base("name=chemreporterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agencylist> agencylists { get; set; }
        public virtual DbSet<atandtassociatedata> atandtassociatedatas { get; set; }
        public virtual DbSet<atandtvolunteerdata> atandtvolunteerdatas { get; set; }
        public virtual DbSet<availablespillid> availablespillids { get; set; }
        public virtual DbSet<basfenvironmental> basfenvironmentals { get; set; }
        public virtual DbSet<basfenvironmentalid> basfenvironmentalids { get; set; }
        public virtual DbSet<basfinjury> basfinjuries { get; set; }
        public virtual DbSet<basfinjuryid> basfinjuryids { get; set; }
        public virtual DbSet<cleanshotid> cleanshotids { get; set; }
        public virtual DbSet<companyinformation> companyinformations { get; set; }
        public virtual DbSet<crest811> crest811 { get; set; }
        public virtual DbSet<crestallnotification> crestallnotifications { get; set; }
        public virtual DbSet<crestdotincident> crestdotincidents { get; set; }
        public virtual DbSet<crester> cresters { get; set; }
        public virtual DbSet<crestgeneralincident> crestgeneralincidents { get; set; }
        public virtual DbSet<cresthighprofileincident> cresthighprofileincidents { get; set; }
        public virtual DbSet<crestmonthlyreport> crestmonthlyreports { get; set; }
        public virtual DbSet<crestpipelinemember> crestpipelinemembers { get; set; }
        public virtual DbSet<crestpiplineincident> crestpiplineincidents { get; set; }
        public virtual DbSet<crestwoodtransportationlist> crestwoodtransportationlists { get; set; }
        public virtual DbSet<generalincidentedit> generalincidentedits { get; set; }
        public virtual DbSet<generalincidentid> generalincidentids { get; set; }
        public virtual DbSet<generalincidentreportdata> generalincidentreportdatas { get; set; }
        public virtual DbSet<globasereportdata> globasereportdatas { get; set; }
        public virtual DbSet<glocountylist> glocountylists { get; set; }
        public virtual DbSet<gloemail> gloemails { get; set; }
        public virtual DbSet<gloid> gloids { get; set; }
        public virtual DbSet<glolastid> glolastids { get; set; }
        public virtual DbSet<y> ies { get; set; }
        public virtual DbSet<iescontact> iescontacts { get; set; }
        public virtual DbSet<knowledgebase> knowledgebases { get; set; }
        public virtual DbSet<modrequest> modrequests { get; set; }
        public virtual DbSet<noncoastal> noncoastals { get; set; }
        public virtual DbSet<oldglo> oldgloes { get; set; }
        public virtual DbSet<otherid> otherids { get; set; }
        public virtual DbSet<reportlog> reportlogs { get; set; }
        public virtual DbSet<shelloilincidentdata> shelloilincidentdatas { get; set; }
        public virtual DbSet<spillorigin> spillorigins { get; set; }
        public virtual DbSet<spillunit> spillunits { get; set; }
        public virtual DbSet<tceqafterhour> tceqafterhours { get; set; }
        public virtual DbSet<tceqreport> tceqreports { get; set; }
        public virtual DbSet<theochemcleanshotincident> theochemcleanshotincidents { get; set; }
        public virtual DbSet<theochemcontactinfo> theochemcontactinfoes { get; set; }
        public virtual DbSet<theochemcontactinformation> theochemcontactinformations { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<veolianonincident> veolianonincidents { get; set; }
        public virtual DbSet<CRMWebU> CRMWebUs { get; set; }
        public virtual DbSet<NorthwindGeneralIncident> NorthwindGeneralIncidents { get; set; }
        public virtual DbSet<NorthwindPipelineIncident> NorthwindPipelineIncidents { get; set; }
    }
}
