//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class modrequest
    {
        public int modrequestid { get; set; }
        public string ersoperator { get; set; }
        public string companyname { get; set; }
        public string nameofcaller { get; set; }
        public string phone { get; set; }
        public string ext { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string sendingmethod { get; set; }
        public string modclient { get; set; }
        public string datereceived { get; set; }
        public string datefulfilled { get; set; }
        public string comments { get; set; }
        public string prodname1 { get; set; }
        public string manu1 { get; set; }
        public string qty1 { get; set; }
        public string locatedvia1 { get; set; }
        public string prodname2 { get; set; }
        public string manu2 { get; set; }
        public string qty2 { get; set; }
        public string locatedvia2 { get; set; }
        public string prodname3 { get; set; }
        public string manu3 { get; set; }
        public string qty3 { get; set; }
        public string locatedvia3 { get; set; }
        public string prodname4 { get; set; }
        public string manu4 { get; set; }
        public string qty4 { get; set; }
        public string locatedvia4 { get; set; }
        public string prodname5 { get; set; }
        public string manu5 { get; set; }
        public string qty5 { get; set; }
        public string locatedvia5 { get; set; }
        public string prodname6 { get; set; }
        public string manu6 { get; set; }
        public string qty6 { get; set; }
        public string locatedvia6 { get; set; }
        public string prodname7 { get; set; }
        public string manu7 { get; set; }
        public string qty7 { get; set; }
        public string locatedvia7 { get; set; }
        public string prodname8 { get; set; }
        public string manu8 { get; set; }
        public string qty8 { get; set; }
        public string locatedvia8 { get; set; }
        public string prodname9 { get; set; }
        public string manu9 { get; set; }
        public string qty9 { get; set; }
        public string locatedvia9 { get; set; }
        public string prodname10 { get; set; }
        public string manu10 { get; set; }
        public string qty10 { get; set; }
        public string locatedvia10 { get; set; }
        public string totalcost { get; set; }
        public string price1 { get; set; }
        public string price2 { get; set; }
        public string price3 { get; set; }
        public string price4 { get; set; }
        public string price5 { get; set; }
        public string price6 { get; set; }
        public string price7 { get; set; }
        public string price8 { get; set; }
        public string price9 { get; set; }
        public string price10 { get; set; }
        public string totalqty { get; set; }
        public string monthreceived { get; set; }
        public string yearreceived { get; set; }
    }
}
