//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class NorthwindGeneralIncident
    {
        public int ID { get; set; }
        public string ERSOperator { get; set; }
        public string CallerName { get; set; }
        public string CallerPhone { get; set; }
        public string EmpOrContract { get; set; }
        public string ContractedCompany { get; set; }
        public System.DateTime CallDate { get; set; }
        public string CallTime { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public string IncidentTime { get; set; }
        public string IncidentTimeZone { get; set; }
        public string IncidentCity { get; set; }
        public string IncidentState { get; set; }
        public string IncidentCounty { get; set; }
        public string FacilityOrProject { get; set; }
        public string IncidentLocation { get; set; }
        public string IncidentNature { get; set; }
        public string WaterbodiesImpacted { get; set; }
        public string ImpactedAreaDetails { get; set; }
        public string IncidentDetails { get; set; }
        public string IndividualSafety { get; set; }
        public string Notify911 { get; set; }
        public string TransportToHospital { get; set; }
        public string MediaOnScene { get; set; }
        public string EmergencyResponders { get; set; }
        public string HSERName { get; set; }
        public string HSERPhone { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public string NotificationTime { get; set; }
        public string InjuryExposureIllness { get; set; }
        public string ChemicalSpillRelease { get; set; }
    }
}
