//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class NorthwindPipelineIncident
    {
        public int ID { get; set; }
        public System.DateTime CallDate { get; set; }
        public string CallTime { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public string IncidentTime { get; set; }
        public string TimeZone { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string GeneralDirectionFrom { get; set; }
        public string ClosestLandmark { get; set; }
        public string Intersection { get; set; }
        public string Observing { get; set; }
        public string Smoke { get; set; }
        public string Flames { get; set; }
        public string Hissing { get; set; }
        public string Liquid { get; set; }
        public string OilSheen { get; set; }
        public string PipelineMarkers { get; set; }
        public string EggOdor { get; set; }
        public string VaporMist { get; set; }
        public string ROWorWellPad { get; set; }
        public string Tanks { get; set; }
        public string Landowner { get; set; }
        public string LeaseWellName { get; set; }
        public string CallerName { get; set; }
        public string CallerPhone { get; set; }
        public string Notify911 { get; set; }
        public string Injuries { get; set; }
        public string ImmediateDanger { get; set; }
        public string RelationToIncident { get; set; }
        public string SafelyWarn { get; set; }
        public string ReportTakerName { get; set; }
        public string ReportTakerEmail { get; set; }
        public string Temperature { get; set; }
        public string WindSpeed { get; set; }
        public string WindDirection { get; set; }
        public string WeatherConditions { get; set; }
        public string NotifiedName { get; set; }
        public string NotifiedNumber { get; set; }
        public string NotifiedEmail { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public string NotificationTime { get; set; }
        public string SeeingHearingSmelling { get; set; }
    }
}
