//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldglo
    {
        public int cntSpillID { get; set; }
        public string fDrill { get; set; }
        public string txtDrillTxt { get; set; }
        public string txtReportTakenBy { get; set; }
        public string txtReportPartyAffliation { get; set; }
        public string datReportTakenDate { get; set; }
        public string datReportTakenTime { get; set; }
        public string txtNotificationAgency { get; set; }
        public string txtDischargeReportedBy { get; set; }
        public string txtDischargePhone1 { get; set; }
        public string txtDischargePhone2 { get; set; }
        public string datDischargeDate { get; set; }
        public string datDischargeTime { get; set; }
        public string txtMaterial1 { get; set; }
        public string dblCASUN1 { get; set; }
        public string dblAmtSpilled1 { get; set; }
        public string txtUnitRecovered1 { get; set; }
        public string txtMaterial2 { get; set; }
        public string dblCASUN2 { get; set; }
        public string dblAmtSpilled2 { get; set; }
        public string txtUnitRecovered2 { get; set; }
        public string txtMaterial3 { get; set; }
        public string dblCASUN3 { get; set; }
        public string dblAmtSpilled3 { get; set; }
        public string txtUnitRecovered3 { get; set; }
        public string txtMaterial4 { get; set; }
        public string dblCASUN4 { get; set; }
        public string dblAmtSpilled4 { get; set; }
        public string txtUnitRecovered4 { get; set; }
        public string txtMaterial5 { get; set; }
        public string dblCASUN5 { get; set; }
        public string dblAmtSpilled5 { get; set; }
        public string txtUnitRecovered5 { get; set; }
        public string wSpillCounty { get; set; }
        public string wOrigin { get; set; }
        public string fSpillInWater { get; set; }
        public string fSpillAirRelease { get; set; }
        public string fCoastalWater { get; set; }
        public string fLand { get; set; }
        public string txtSpillReceivingWater { get; set; }
        public string dblSpillAmountInWater { get; set; }
        public string txtSpillAmountInWaterUnits { get; set; }
        public string memSpillLocation { get; set; }
        public string dblRRCLeaseNumber { get; set; }
        public string txtRRCLeaseName { get; set; }
        public string txtRRCFieldName { get; set; }
        public string txtLandOwner { get; set; }
        public string memActionsTakenCleanUpStatus { get; set; }
        public string txtNRCNumber { get; set; }
        public string txtAgencyName1 { get; set; }
        public string txtAgencyName2 { get; set; }
        public string txtAgencyName3 { get; set; }
        public string datDate1 { get; set; }
        public string datDate2 { get; set; }
        public string datDate3 { get; set; }
        public string txtWhere1 { get; set; }
        public string txtWhere2 { get; set; }
        public string txtWhere3 { get; set; }
        public string txtWho1 { get; set; }
        public string txtWho2 { get; set; }
        public string txtWho3 { get; set; }
        public string datTime1 { get; set; }
        public string datTime2 { get; set; }
        public string datTime3 { get; set; }
        public string txtSpiller { get; set; }
        public string txtSpillerAddress { get; set; }
        public string txtSpillerCity { get; set; }
        public string txtSpillerState { get; set; }
        public string txtSpillerZipCode { get; set; }
        public string txtSpillerContact { get; set; }
        public string txtSpillerContactPhone { get; set; }
        public string memComments { get; set; }
        public string txtAgcyName1 { get; set; }
        public string txtAgcyName2 { get; set; }
        public string txtAgcyName3 { get; set; }
        public string datD1 { get; set; }
        public string datD2 { get; set; }
        public string datD3 { get; set; }
        public string txtWhr1 { get; set; }
        public string txtWhr2 { get; set; }
        public string txtWhr3 { get; set; }
        public string txtW1 { get; set; }
        public string txtW2 { get; set; }
        public string txtW3 { get; set; }
        public string datTi1 { get; set; }
        public string datTi2 { get; set; }
        public string datTi3 { get; set; }
        public string txtLastField { get; set; }
    }
}
