//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportlog
    {
        public int ReportLogID { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public int MinutesTaken { get; set; }
        public string Operator { get; set; }
        public string ReportType { get; set; }
        public string ReportID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public byte[] Corrected { get; set; }
    }
}
