//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class shelloilincidentdata
    {
        public int incid { get; set; }
        public string ersop { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string callername1 { get; set; }
        public string callername2 { get; set; }
        public string callername3 { get; set; }
        public string callerphone1 { get; set; }
        public string callerphone2 { get; set; }
        public string callerphone3 { get; set; }
        public string callerext1 { get; set; }
        public string callerext2 { get; set; }
        public string callerext3 { get; set; }
        public string calleraltphone1 { get; set; }
        public string calleraltphone2 { get; set; }
        public string calleraltphone3 { get; set; }
        public string calleraltext1 { get; set; }
        public string calleraltext2 { get; set; }
        public string calleraltext3 { get; set; }
        public string comments { get; set; }
        public string staffname { get; set; }
        public string staffphone { get; set; }
        public string staffext { get; set; }
        public string staffreporttime { get; set; }
        public string stafftimezone { get; set; }
        public string followupname1 { get; set; }
        public string followupname2 { get; set; }
        public string followupname3 { get; set; }
        public string followupname4 { get; set; }
        public string followupname5 { get; set; }
        public string followuptime1 { get; set; }
        public string followuptime2 { get; set; }
        public string followuptime3 { get; set; }
        public string followuptime4 { get; set; }
        public string followuptime5 { get; set; }
        public string followuptimezone1 { get; set; }
        public string followuptimezone2 { get; set; }
        public string followuptimezone3 { get; set; }
        public string followuptimezone4 { get; set; }
        public string followuptimezone5 { get; set; }
        public string followupphone1 { get; set; }
        public string followupphone2 { get; set; }
        public string followupphone3 { get; set; }
        public string followupphone4 { get; set; }
        public string followupphone5 { get; set; }
        public string followupext1 { get; set; }
        public string followupext2 { get; set; }
        public string followupext3 { get; set; }
        public string followupext4 { get; set; }
        public string followupext5 { get; set; }
        public string emailsent { get; set; }
        public string notes { get; set; }
    }
}
