//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class tceqafterhour
    {
        public int ID { get; set; }
        public string Region { get; set; }
        public string PrimaryContact { get; set; }
        public string SecondaryContact { get; set; }
        public string TertiaryContact { get; set; }
        public string RegionalDirector { get; set; }
        public string EmailAddress { get; set; }
    }
}
