//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class tceqreport
    {
        public int id { get; set; }
        public string Operator { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string ReportTime { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public string IncidentTime { get; set; }
        public string ReportedBy { get; set; }
        public string ContactNumber { get; set; }
        public string ContactNumber2 { get; set; }
        public string Emergency { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string County { get; set; }
        public string MediaAffected { get; set; }
        public string ReceivingWater { get; set; }
        public string AmountWater { get; set; }
        public string UnitWater { get; set; }
        public string PRCompany { get; set; }
        public string PRStreet { get; set; }
        public string PRCity { get; set; }
        public string PRState { get; set; }
        public string PRZipCode { get; set; }
        public string PRContact { get; set; }
        public string PRPhone { get; set; }
        public string Material1 { get; set; }
        public string Material2 { get; set; }
        public string Material3 { get; set; }
        public string Material4 { get; set; }
        public string Material5 { get; set; }
        public string CAS1 { get; set; }
        public string CAS2 { get; set; }
        public string CAS3 { get; set; }
        public string CAS4 { get; set; }
        public string CAS5 { get; set; }
        public string Amount1 { get; set; }
        public string Amount2 { get; set; }
        public string Amount3 { get; set; }
        public string Amount4 { get; set; }
        public string Amount5 { get; set; }
        public string Unit1 { get; set; }
        public string Unit2 { get; set; }
        public string Unit3 { get; set; }
        public string Unit4 { get; set; }
        public string Unit5 { get; set; }
        public string ResponderName { get; set; }
        public string NotificationTime { get; set; }
    }
}
