//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class theochemcleanshotincident
    {
        public string incidentId { get; set; }
        public string ersOp { get; set; }
        public string rptDate { get; set; }
        public string rptTime { get; set; }
        public string callerName { get; set; }
        public string callerPhone { get; set; }
        public string callerAff { get; set; }
        public string callerFaxEmail { get; set; }
        public string incStreet { get; set; }
        public string incCity { get; set; }
        public string incState { get; set; }
        public string incCountry { get; set; }
        public string incTimeZone { get; set; }
        public string incDate { get; set; }
        public string incTime { get; set; }
        public string quest1 { get; set; }
        public string quest2Qty { get; set; }
        public string quest2Units { get; set; }
        public string quest3 { get; set; }
        public string quest4 { get; set; }
        public string quest5 { get; set; }
        public string quest6 { get; set; }
        public string quest7 { get; set; }
        public string quest8 { get; set; }
        public string quest9 { get; set; }
        public string quest10YesOrNo { get; set; }
        public string quest10IfYesWhat { get; set; }
        public string quest11YesOrNo { get; set; }
        public string quest11IfYesWhat { get; set; }
        public string quest12 { get; set; }
        public string quest13 { get; set; }
        public string quest14 { get; set; }
        public string quest15 { get; set; }
        public string quest16 { get; set; }
        public string quest17 { get; set; }
        public string additCommentsDetails { get; set; }
        public string subName { get; set; }
        public string subAdminContact { get; set; }
        public string subPhone { get; set; }
        public string subFax { get; set; }
        public string subEmail { get; set; }
        public string subAddress { get; set; }
        public string subCityStateZip { get; set; }
        public string emailsent { get; set; }
        public string comments { get; set; }
        public string type { get; set; }
    }
}
