//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class veolianonincident
    {
        public int id { get; set; }
        public string callername { get; set; }
        public string callerphonenumber { get; set; }
        public string calleraffiliation { get; set; }
        public string incidentcity { get; set; }
        public string incidentstate { get; set; }
        public string description { get; set; }
        public string ersoperator { get; set; }
        public string date { get; set; }
        public string time { get; set; }
    }
}
