//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class y
    {
        public int id { get; set; }
        public string emergency { get; set; }
        public string facilityname { get; set; }
        public string location { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string callername { get; set; }
        public string callerphonenumber { get; set; }
        public string contactonscenename { get; set; }
        public string contactonscenephonenumber { get; set; }
        public string callerunknown { get; set; }
        public string contactunknown { get; set; }
    }
}
