//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crm.chemtelinc.com.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=chemdb1.c8ujbgtllu2u.us-east-2.rds.amazonaws.com;Initial Catalog=chem" +
            "reportertest;Persist Security Info=True;User ID=admin;Password=LrtcXcIvlnNlWNDDe" +
            "Arq")]
        public string chemicalTestConnectionString {
            get {
                return ((string)(this["chemicalTestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=chemdb1.c8ujbgtllu2u.us-east-2.rds.amazonaws.com;Initial Catalog=stat" +
            "esdb;Persist Security Info=True;User ID=admin;Password=LrtcXcIvlnNlWNDDeArq\n")]
        public string StatesConnectionString {
            get {
                return ((string)(this["StatesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=chemdb1.c8ujbgtllu2u.us-east-2.rds.amazonaws.com;Initial Catalog=chem" +
            "reporter;Persist Security Info=True;User ID=admin;Password=LrtcXcIvlnNlWNDDeArq")]
        public string chemicalConnectionString {
            get {
                return ((string)(this["chemicalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=chemdb1.c8ujbgtllu2u.us-east-2.rds.amazonaws.com;Initial Catalog=Gold" +
            "mine_Main;Persist Security Info=True;User ID=admin;Password=LrtcXcIvlnNlWNDDeArq" +
            "")]
        public string GoldmineConnectionString {
            get {
                return ((string)(this["GoldmineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=chemdb1.c8ujbgtllu2u.us-east-2.rds.amazonaws.com;Initial Catalog=Cust" +
            "omSites;Persist Security Info=True;User ID=admin;Password=LrtcXcIvlnNlWNDDeArq")]
        public string CustomSitesConnectionString {
            get {
                return ((string)(this["CustomSitesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=chemdb1.c8ujbgtllu2u.us-east-2.rds.amazonaws.com;Initial Catalog=vdoc" +
            "s;Persist Security Info=True;User ID=admin;Password=LrtcXcIvlnNlWNDDeArq")]
        public string VdocConnectionString {
            get {
                return ((string)(this["VdocConnectionString"]));
            }
        }
    }
}
